# Классификация (2-ая часть)

#### Заметим, что в прошлой части все признаки были взяты как бинарные. Но ведь признаки также могут быть дискретными, то есть принимать значения не только 0 и 1, но от 0 до k-1. Тогда код программы фактически остается прежним (стоит лишь по-другому вводить данные в программу). В качестве примера рассмотрим задачу про выдачу кредитов. Даны два списка клиентов банка и их характеристики. Клиентам из первого списка кредит был одобрен, клиентам из второго - отклонен. Необходимо выяснить, какие признаки сильнее других влияют на выдачу кредита и классифицировать новых заемщиков.
#### Первая таблица - список клиентов, кому был одобрен кредит, вторая таблица - список тех, кому кредит был отклонен

In [3]:
import pandas as pd
example10 = pd.DataFrame({'образование': ['высшее', 'неполное высшее', 'среднее', 'высшее', 'среднее', 'высшее', 'высшее', 'высшее', 'неполное среднее', 'среднее', 'неполное высшее', 'среднее'], 'доход': ['50-100k', '30-50k', '10-30k', 'выше 300k', '100-300k', '100-300k', '30-50k', '50-100k', 'меньше 10k', '100-300k', '50-100k', 'выше 300k'], 'сумма займа': ['50-100k', 'меньше 50k', 'меньше 50k', '1-3M', '200-500k', 'меньше 50k', 'меньше 50k', '50-100k', 'меньше 50k', '100-200k', '50-100k', '500-1000k'], 'поручитель': ['есть', 'нет', 'нет', 'есть', 'нет', 'есть', 'есть', 'есть', 'есть', 'нет', 'нет', 'нет'], 'текущие задолженности': ['отсутствуют', 'отсутствуют', 'отсутствуют', 'отсутствуют', 'отсутствуют', '50-100k', 'отсутствуют', 'меньше 50k', 'отсутствуют', 'меньше 50k', 'отсутствуют', 'отсутствуют'], 'постоянное место работы': ['есть', 'есть', 'есть', 'есть', 'есть', 'есть', 'нет', 'есть', 'есть', 'есть', 'есть', 'есть']})
example10 = example10.style.set_properties(**{'font-size': '14pt'})
example10

In [4]:
example11 = pd.DataFrame({'образование': ['среднее', 'неполное среднее', 'высшее', 'неполное высшее', 'среднее', 'среднее', 'неполное высшее', 'высшее', 'неполное среднее', 'среднее', 'высшее', 'среднее'], 'доход': ['меньше 10k', '10-30k', 'меньше 10k', '30-50k', 'меньше 10k', '30-50k', '10-30k', '10-30k', '30-50k', '50-100k', '10-30k', '30-50k'], 'сумма займа': ['200-500k', '500-1000k', '1-3M', 'выше 3M', '1-3M', '500-1000k', '50-100k', '100-200k', 'выше 3M', '1-3M', 'выше 3M', '1-3M'], 'поручитель': ['нет', 'нет', 'нет', 'нет', 'есть', 'нет', 'нет', 'нет', 'нет', 'нет', 'есть', 'нет'], 'текущие задолженности': ['50-100k', 'выше 500k', 'отсутствуют', 'отсутствуют', 'выше 500k', 'меньше 50k', '100-500k', '50-100k', 'меньше 50k', 'выше 500k', '100-500k', 'отсутствуют'], 'постоянное место работы': ['есть', 'нет', 'есть', 'нет', 'есть', 'есть', 'нет', 'есть', 'есть', 'есть', 'есть', 'есть']})
example11 = example11.style.set_properties(**{'font-size': '14pt'})
example11

#### Построив решетки и сформировав гипотезы, получаем:
#### Положительные гипотезы:
##### поручитель И отсутствие задолженностей
##### сумма займа меньше 50k
##### доход 100-300k И постоянное место работы
##### неполное высшее образование И нет поручителя И отсутствие долгов И постоянное место работы
##### доход 50-100k И сумма займа 50-100k И постоянное место работы 
##### доход выше 300k И отсутствие задолженностей И постоянное место работы
#### Отрицательные гипотезы:
##### доход меньше 10k И нет поручителя И постоянное место работы
##### среднее образование И доход меньше 10k И постоянное место работы
##### доход меньше 10k И сумма займа 1-3M И постоянное место работы
##### нет поручителя И нет постоянного места работы
##### нет поручителя И задолженность 50-100k И постоянное место работы
##### высшее образование И нет поручителя И постоянное место работы
##### неполное среднее образование И нет поручителя
##### доход 30-50k И нет поручителя И задолженность меньше 50k И постоянное место работы
##### задолженность выше 500k
##### доход 10-30k И задолженность 100-500k
##### высшее образование И доход 10-30k И постоянное место работы
##### сумма займа больше 3M
##### среднее образование И доход 30-50k И нет поручителя И постоянное место работы
##### сумма займа 1-3M И нет поручителя И постоянное место работы
##### среднее образование И сумма займа 1-3M И постоянное место работы
#### Теперь попробуем классифицировать новых клиентов:

In [5]:
example12 = pd.DataFrame({'образование': ['высшее', 'среднее', 'среднее',  'среднее', 'высшее'], 'доход': ['10-30k', 'меньше 10k', '100-300k', '10-30k', 'выше 300k'], 'сумма займа': ['100-200k', '500-1000k', 'меньше 50k', '100-200k', 'меньше 50k'], 'поручитель': ['есть', 'нет', 'нет', 'нет', 'нет'], 'текущие задолженности': ['отсутствуют', '100-500k', 'отсутствуют', '100-500k', 'выше 500k'], 'постоянное место работы': ['есть', 'нет', 'есть', 'есть', 'есть'], 'ЗАЙМ': ['одобрено', 'отклонено', 'одобрено', 'отклонено', 'отклонено']})
example12 = example12.style.set_properties(**{'font-size': '14pt'})
example12

## Устойчивость к шуму

#### Заметим, что текущий алгоритм неустойчив к шуму. Тогда попробуем усовершенствовать его, используя метод RULEARNER. В моем случае некоторые объекты обучающей выборки будут рассматриваться как ненадежные. Тогда, сформивовав решетку формальных понятий, обозначим неблагонадежными все понятия, объекты которых содержат только один объект, и он является ненадежным, остальные понятия будем считать благонадежными. Далее будем подниматься по решетке понятий, и для каждой вершины будем считать, сколько неблаго-/благонадежных вершин в их нижнем конусе (верхним конусом вершины называется множество вершин, включая данную, которые могут быть достигнуты от данной вершины, поднимаясь только по восходящим ребрам, нижним конусом вершины называется множество вершин, которые содержат данную вершину в своем верхнем конусе). Тогда, если процент неблагонадженых вершин не превышает некоторого заранее заданного параметра, то и сама эта вершина является благонадежной, в противном случае, неблагонадежной. Неблагонадежные понятия не участвуют в формировании гипотез. Таким образом удается понизить влияние шума на формирование гипотез и на качество работы алгоритма

In [ ]:
def rulearner(lattice, graph, broken, percent):
    lattice_h = [1] * len(lattice)
    for i in range(1, len(lattice)):
        if len(lattice[i][0]) == 1:
            if lattice[i][0][0] in broken:
                lattice_h[i] = 0
            else:
                lattice_h[i] = 1
        else:
            truesum = 0
            falsesum = 0
            peaks = set()
            peaks.add(i)
            for edge in graph[::-1]:
                if edge[1] in peaks and edge[0] not in peaks:
                    peaks.add(edge[0])
                    if lattice_h[edge[0]]:
                        truesum += 1
                    else:
                        falsesum += 1
            if 100 * falsesum / (truesum + falsesum) > percent:
                lattice_h[i] = 0
    return lattice_h

#### Также в формировании гипотез этот код

In [ ]:
for i in lattice_plus[1:]:
    hypotheses_plus = np.vstack((hypotheses_plus, i[1]))

#### меняется на этот

In [ ]:
for i in range(1, len(lattice_plus)):
    if rulearner_plus[i]:
        hypotheses_plus = np.vstack((hypotheses_plus, lattice_plus[i][1]))

## Временная сложность 
#### Так как операция построения алгебраической решетки требует пройтись циклом по всем возможным пересечениям объектов, то это уже дает экспоненциальную сложность алгоритму. Также для каждого пересечения объектов мы должны построить вектор признаков, объединяя векторы признаков всех объектов, которые входят в исходное пересечение. Помимо этого, для правильного построения решетки, для каждого вектора признаков необходимо найти наибольшее возможное пересечение объектов, которым присущ данный вектор признаков. Обе эти операции дают еще множитель n в оценке сложности. В итоге получаем, что временная сложность алгоритма $O(n * 2^{n})$. Проведем исследование: протестируем алгоритм построения решетки на разных данных и посмотрим, сколько времени необходимо, чтобы он успешно выполнился

In [8]:
experiment = pd.DataFrame({'$n$': [10, 12, 13, 14, 15, 16], 'секунды': ['<1', 1.5, 2.5, 6, 12, 25]})
experiment

   $n$ секунды
0   10      <1
1   12     1.5
2   13     2.5
3   14       6
4   15      12
5   16      25

#### Как видно из таблицы, алгоритм действительно имеет экспоненциальную сложность, и увеличение входных данных $n$ на $k$ увеличивает время выполнения алгоритма в $2^k$ раза. Такая временная сложность делает невозможным применение алгоритма для решения задач с большим количеством данных. Также стоит упомянуть, что существуют другие алгоритмы анализа формальных понятий, которые могут иметь меньшую временную сложность, например, алгоритм LEGAL, который строит не всю решетку, а лишь полурешетку